// <auto-generated />
using System;
using System.Text.Json;
using BBB_ApplicationDashboard.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BBB_ApplicationDashboard.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251105194848_AddSecondaryBusinessTypesInAccreditation")]
    partial class AddSecondaryBusinessTypesInAccreditation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BBB_ApplicationDashboard.Domain.Entities.Accreditation", b =>
                {
                    b.Property<Guid>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalBusinessInformation")
                        .HasColumnType("text");

                    b.Property<string>("ApplicationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ApplicationStatusExternal")
                        .HasColumnType("integer");

                    b.Property<int>("ApplicationStatusInternal")
                        .HasColumnType("integer");

                    b.Property<string>("AvgCustomersPerYear")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BID")
                        .HasColumnType("text");

                    b.Property<string>("BlueApplicationID")
                        .HasColumnType("text");

                    b.Property<string>("BusinessAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusinessAptSuite")
                        .HasColumnType("text");

                    b.Property<string>("BusinessCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusinessDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusinessEntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusinessServiceArea")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("BusinessStartDate")
                        .HasColumnType("date");

                    b.Property<string>("BusinessState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusinessType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusinessZip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyRecordID")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DoingBusinessAs")
                        .HasColumnType("text");

                    b.Property<string>("EIN")
                        .HasColumnType("text");

                    b.Property<string>("EmailToReceiveQuoteRequestsFromCustomers")
                        .HasColumnType("text");

                    b.Property<long>("GrossAnnualRevenue")
                        .HasColumnType("bigint");

                    b.Property<string>("HubSpotApplicationID")
                        .HasColumnType("text");

                    b.Property<string>("Licenses")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("MailingAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MailingCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MailingState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MailingZip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberOfFullTimeEmployees")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberOfLocations")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfPartTimeEmployees")
                        .HasColumnType("integer");

                    b.Property<int>("PartnershipSource")
                        .HasColumnType("integer");

                    b.Property<string>("PreferredContactMethod")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryBusinessEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryBusinessPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryContactEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryContactNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryContactTypes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateOnly>("PrimaryDateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("PrimaryFirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryLastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecondaryBusinessTypes")
                        .HasColumnType("jsonb");

                    b.Property<string>("SecondaryContactTypes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SecondaryEmail")
                        .HasColumnType("text");

                    b.Property<string>("SecondaryFirstName")
                        .HasColumnType("text");

                    b.Property<string>("SecondaryLastName")
                        .HasColumnType("text");

                    b.Property<string>("SecondaryPhone")
                        .HasColumnType("text");

                    b.Property<string>("SecondaryPreferredContactMethod")
                        .HasColumnType("text");

                    b.Property<string>("SecondaryTitle")
                        .HasColumnType("text");

                    b.Property<string>("SocialMediaLinks")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SubmittedByEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubmittedByName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubmittedByTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrackingLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("ApplicationId");

                    b.HasIndex("ApplicationNumber");

                    b.ToTable("Accreditations");
                });

            modelBuilder.Entity("BBB_ApplicationDashboard.Domain.Entities.ActivityEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EntityIdentifier")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Env")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Production");

                    b.Property<JsonDocument>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SyncSource")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("OnlineSync");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UserVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("activity_events");
                });

            modelBuilder.Entity("BBB_ApplicationDashboard.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCSVSync")
                        .HasColumnType("boolean");

                    b.Property<int>("UserSource")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BBB_ApplicationDashboard.Domain.Session", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("SessionSource")
                        .HasColumnType("integer");

                    b.HasKey("Token");

                    b.ToTable("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
